"""initial schema

Revision ID: 787cd71d6603
Revises: 
Create Date: 2026-04-27 11:01:37.695334

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '787cd71d6603'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=140), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    op.create_table('emailsubscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailsubscription_email'), 'emailsubscription', ['email'], unique=True)
    op.create_table('paymentwebhookevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('provider_event_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymentwebhookevent_event_key'), 'paymentwebhookevent', ['event_key'], unique=True)
    op.create_index(op.f('ix_paymentwebhookevent_reference'), 'paymentwebhookevent', ['reference'], unique=False)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('admin_role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('admin_permissions', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('google_sub', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_table('product',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=220), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('voltage_spec', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=False),
    sa.Column('tech_specs', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    op.create_index(op.f('ix_product_slug'), 'product', ['slug'], unique=True)
    op.create_table('tokenblacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokenblacklist_token'), 'tokenblacklist', ['token'], unique=True)
    op.create_index(op.f('ix_tokenblacklist_user_id'), 'tokenblacklist', ['user_id'], unique=False)
    op.create_table('twofactorsecret',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twofactorsecret_user_id'), 'twofactorsecret', ['user_id'], unique=True)
    op.create_table('cartitem',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartitem_product_id'), 'cartitem', ['product_id'], unique=False)
    op.create_index(op.f('ix_cartitem_user_id'), 'cartitem', ['user_id'], unique=False)
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderitem_order_id'), 'orderitem', ['order_id'], unique=False)
    op.create_table('orderreturn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderreturn_order_id'), 'orderreturn', ['order_id'], unique=False)
    op.create_index(op.f('ix_orderreturn_user_id'), 'orderreturn', ['user_id'], unique=False)
    op.create_table('paymentintent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymentintent_order_id'), 'paymentintent', ['order_id'], unique=False)
    op.create_index(op.f('ix_paymentintent_reference'), 'paymentintent', ['reference'], unique=True)
    op.create_index(op.f('ix_paymentintent_user_id'), 'paymentintent', ['user_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=140), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_product_id'), 'review', ['product_id'], unique=False)
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    op.create_table('wishlistitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlistitem_product_id'), 'wishlistitem', ['product_id'], unique=False)
    op.create_index(op.f('ix_wishlistitem_user_id'), 'wishlistitem', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlistitem_user_id'), table_name='wishlistitem')
    op.drop_index(op.f('ix_wishlistitem_product_id'), table_name='wishlistitem')
    op.drop_table('wishlistitem')
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_index(op.f('ix_review_product_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_paymentintent_user_id'), table_name='paymentintent')
    op.drop_index(op.f('ix_paymentintent_reference'), table_name='paymentintent')
    op.drop_index(op.f('ix_paymentintent_order_id'), table_name='paymentintent')
    op.drop_table('paymentintent')
    op.drop_index(op.f('ix_orderreturn_user_id'), table_name='orderreturn')
    op.drop_index(op.f('ix_orderreturn_order_id'), table_name='orderreturn')
    op.drop_table('orderreturn')
    op.drop_index(op.f('ix_orderitem_order_id'), table_name='orderitem')
    op.drop_table('orderitem')
    op.drop_index(op.f('ix_cartitem_user_id'), table_name='cartitem')
    op.drop_index(op.f('ix_cartitem_product_id'), table_name='cartitem')
    op.drop_table('cartitem')
    op.drop_index(op.f('ix_twofactorsecret_user_id'), table_name='twofactorsecret')
    op.drop_table('twofactorsecret')
    op.drop_index(op.f('ix_tokenblacklist_user_id'), table_name='tokenblacklist')
    op.drop_index(op.f('ix_tokenblacklist_token'), table_name='tokenblacklist')
    op.drop_table('tokenblacklist')
    op.drop_index(op.f('ix_product_slug'), table_name='product')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_paymentwebhookevent_reference'), table_name='paymentwebhookevent')
    op.drop_index(op.f('ix_paymentwebhookevent_event_key'), table_name='paymentwebhookevent')
    op.drop_table('paymentwebhookevent')
    op.drop_index(op.f('ix_emailsubscription_email'), table_name='emailsubscription')
    op.drop_table('emailsubscription')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
