"""add_user_email_field

Revision ID: a83bbcaf54ed
Revises: 
Create Date: 2026-04-10 07:58:04.677395

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a83bbcaf54ed'
# NOTE: This repository originally had two Alembic roots:
# - 787cd71d6603 (the real initial schema)
# - a83bbcaf54ed (a legacy placeholder)
#
# On a fresh database, Alembic would try to upgrade from the legacy root first,
# which led to missing core tables (like "order") later in the chain.
# We re-root this legacy revision under the real initial schema so upgrades
# always create the full baseline tables first.
down_revision = '787cd71d6603'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
