"""align schema with architecture

Revision ID: f55ebb63af35
Revises: d41ce5bf95a7
Create Date: 2026-04-27 16:41:26.384098

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f55ebb63af35'
down_revision = 'd41ce5bf95a7'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paymentintent_order_id', table_name='paymentintent')
    op.drop_index('ix_paymentintent_reference', table_name='paymentintent')
    op.drop_index('ix_paymentintent_user_id', table_name='paymentintent')
    op.drop_table('paymentintent')
    op.drop_index('ix_paymentwebhookevent_event_key', table_name='paymentwebhookevent')
    op.drop_index('ix_paymentwebhookevent_reference', table_name='paymentwebhookevent')
    op.drop_table('paymentwebhookevent')
    op.add_column('cartitem', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cartitem_variant_id'), 'cartitem', ['variant_id'], unique=False)
    op.create_foreign_key(None, 'cartitem', 'productvariant', ['variant_id'], ['id'])
    op.add_column('emailsubscription', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('emailsubscription', sa.Column('subscribed_at', sa.DateTime(), nullable=False))
    op.add_column('emailsubscription', sa.Column('unsubscribed_at', sa.DateTime(), nullable=True))
    op.add_column('emailsubscription', sa.Column('verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('emailsubscription', sa.Column('verified', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_emailsubscription_user_id'), 'emailsubscription', ['user_id'], unique=False)
    op.create_index(op.f('ix_emailsubscription_verification_token'), 'emailsubscription', ['verification_token'], unique=False)
    # op.create_foreign_key(None, 'emailsubscription', 'user', ['user_id'], ['id'])
    # op.drop_column('emailsubscription', 'created_at')
    op.add_column('order', sa.Column('total_price', sa.Float(), nullable=True))
    op.execute("UPDATE \"order\" SET total_price = total_amount WHERE total_price IS NULL")
    op.alter_column('order', 'total_price', nullable=False)
    
    op.add_column('order', sa.Column('subtotal_amount', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('delivery_fee', sa.Float(), nullable=True))
    op.execute("UPDATE \"order\" SET delivery_fee = 0.0 WHERE delivery_fee IS NULL")
    op.alter_column('order', 'delivery_fee', nullable=False)
    op.add_column('order', sa.Column('shipping_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('shipping_region', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('shipping_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('shipping_contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('shipping_contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('shipping_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('shipping_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('tracking_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('estimated_delivery', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('cancel_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('paystack_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE \"order\" SET payment_status = 'pending' WHERE payment_status IS NULL")
    op.alter_column('order', 'payment_status', nullable=False)
    
    op.add_column('order', sa.Column('confirmation_email_sent_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))

    op.add_column('order', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE \"order\" SET updated_at = NOW() WHERE updated_at IS NULL")
    op.alter_column('order', 'updated_at', nullable=False)

    op.create_index(op.f('ix_order_idempotency_key'), 'order', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_order_paystack_reference'), 'order', ['paystack_reference'], unique=False)

    op.add_column('orderitem', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.add_column('orderitem', sa.Column('variant_name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True))
    op.add_column('orderitem', sa.Column('variant_image_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    op.add_column('orderitem', sa.Column('variant_detail_snapshot', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True))
    op.add_column('orderitem', sa.Column('price_at_purchase', sa.Float(), nullable=True))
    op.execute("UPDATE orderitem SET price_at_purchase = unit_price WHERE price_at_purchase IS NULL")
    op.alter_column('orderitem', 'price_at_purchase', nullable=False)

    op.add_column('review', sa.Column('verified_purchase', sa.Boolean(), nullable=True))
    op.add_column('review', sa.Column('helpful_count', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE review SET verified_purchase = false WHERE verified_purchase IS NULL")
    op.execute("UPDATE review SET helpful_count = 0 WHERE helpful_count IS NULL")
    op.execute("UPDATE review SET updated_at = NOW() WHERE updated_at IS NULL")
    op.alter_column('review', 'verified_purchase', nullable=False)
    op.alter_column('review', 'helpful_count', nullable=False)
    op.alter_column('review', 'updated_at', nullable=False)

    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email_is_placeholder', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('two_fa_enabled', sa.Boolean(), nullable=True))
    op.execute("UPDATE \"user\" SET email_verified = is_email_verified WHERE email_verified IS NULL")
    op.execute("UPDATE \"user\" SET email_is_placeholder = false WHERE email_is_placeholder IS NULL")
    op.execute("UPDATE \"user\" SET two_fa_enabled = false WHERE two_fa_enabled IS NULL")
    op.alter_column('user', 'email_verified', nullable=False)
    op.alter_column('user', 'email_is_placeholder', nullable=False)
    op.alter_column('user', 'two_fa_enabled', nullable=False)

    op.add_column('user', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('two_fa_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('shipping_region', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True))
    op.add_column('user', sa.Column('shipping_city', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True))
    op.add_column('user', sa.Column('shipping_address_line1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('shipping_address_line2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('shipping_landmark', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('shipping_contact_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True))
    op.add_column('user', sa.Column('shipping_contact_phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE \"user\" SET username = split_part(email, '@', 1) WHERE username IS NULL")
    op.execute("UPDATE \"user\" SET username = 'user_' || id::text WHERE username IS NULL OR username = ''")
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=120),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'admin_permissions',
               existing_type=sa.VARCHAR(length=4000),
               nullable=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_constraint('user_google_sub_key', 'user', type_='unique')
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_deleted_at'), 'user', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_google_sub'), 'user', ['google_sub'], unique=True)
    op.create_unique_constraint(None, 'user', ['email'])
    
    # Data Migration: Copy data from old columns to new columns before dropping them
    # Use EXECUTE for safety in case columns are missing in some environments
    op.execute("UPDATE orderitem SET price_at_purchase = unit_price")

    op.drop_column('order', 'total_amount')
    op.drop_column('orderitem', 'unit_price')
    # op.drop_column('user', 'password_hash')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'is_email_verified')
    
    op.create_unique_constraint('uq_wishlistitem_user_product', 'wishlistitem', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wishlistitem_user_product', 'wishlistitem', type_='unique')
    op.add_column('user', sa.Column('is_email_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # op.add_column('user', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_google_sub'), table_name='user')
    op.drop_index(op.f('ix_user_deleted_at'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_unique_constraint('user_google_sub_key', 'user', ['google_sub'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.alter_column('user', 'admin_permissions',
               existing_type=sa.VARCHAR(length=4000),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'shipping_contact_phone')
    op.drop_column('user', 'shipping_contact_name')
    op.drop_column('user', 'shipping_landmark')
    op.drop_column('user', 'shipping_address_line2')
    op.drop_column('user', 'shipping_address_line1')
    op.drop_column('user', 'shipping_city')
    op.drop_column('user', 'shipping_region')
    op.drop_column('user', 'two_fa_method')
    op.drop_column('user', 'two_fa_enabled')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'email_is_placeholder')
    op.drop_column('user', 'email_verified')
    # op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'name')
    op.drop_column('twofactorsecret', 'backup_codes')
    op.drop_column('review', 'updated_at')
    op.drop_column('review', 'helpful_count')
    op.drop_column('review', 'verified_purchase')
    # op.add_column('product', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # op.add_column('product', sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.add_column('product', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # op.add_column('product', sa.Column('currency', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    # op.add_column('product', sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # op.create_foreign_key('product_category_id_fkey', 'product', 'category', ['category_id'], ['id'])
    op.drop_index(op.f('ix_product_deleted_at'), table_name='product')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.create_index('ix_product_sku', 'product', ['sku'], unique=True)
    op.create_index('ix_product_slug', 'product', ['slug'], unique=True)
    op.create_index('ix_product_name', 'product', ['name'], unique=False)
    # op.create_index('ix_product_category_id', 'product', ['category_id'], unique=False)
    op.alter_column('product', 'sku',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('product', 'deleted_at')
    op.drop_column('product', 'avg_rating')
    op.drop_column('product', 'sales_count')
    # op.drop_column('product', 'in_stock')
    op.drop_column('product', 'weight')
    # op.drop_column('product', 'category')
    op.drop_constraint(None, 'orderreturn', type_='foreignkey')
    op.drop_index(op.f('ix_orderreturn_status'), table_name='orderreturn')
    op.drop_index(op.f('ix_orderreturn_resolved_by'), table_name='orderreturn')
    op.alter_column('orderreturn', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=24),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('orderreturn', 'reason',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=120),
               type_=sa.VARCHAR(length=240),
               existing_nullable=False)
    op.drop_column('orderreturn', 'updated_at')
    op.drop_column('orderreturn', 'resolved_at')
    op.drop_column('orderreturn', 'resolved_by')
    op.drop_column('orderreturn', 'admin_notes')
    op.drop_column('orderreturn', 'preferred_outcome')
    op.drop_column('orderreturn', 'details')
    op.add_column('orderitem', sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_index(op.f('ix_orderitem_variant_id'), table_name='orderitem')
    op.drop_column('orderitem', 'price_at_purchase')
    op.drop_column('orderitem', 'variant_detail_snapshot')
    op.drop_column('orderitem', 'variant_image_url')
    op.drop_column('orderitem', 'variant_name')
    op.drop_column('orderitem', 'variant_id')
    op.add_column('order', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_order_paystack_reference'), table_name='order')
    op.drop_index(op.f('ix_order_idempotency_key'), table_name='order')
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'idempotency_key')
    op.drop_column('order', 'confirmation_email_sent_at')
    op.drop_column('order', 'payment_status')
    op.drop_column('order', 'paystack_reference')
    op.drop_column('order', 'notes')
    op.drop_column('order', 'payment_method')
    op.drop_column('order', 'cancel_reason')
    op.drop_column('order', 'delivered_at')
    op.drop_column('order', 'estimated_delivery')
    op.drop_column('order', 'tracking_number')
    op.drop_column('order', 'shipping_provider')
    op.drop_column('order', 'shipping_address')
    op.drop_column('order', 'shipping_contact_phone')
    op.drop_column('order', 'shipping_contact_name')
    op.drop_column('order', 'shipping_city')
    op.drop_column('order', 'shipping_region')
    op.drop_column('order', 'shipping_method')
    op.drop_column('order', 'delivery_fee')
    op.drop_column('order', 'subtotal_amount')
    op.drop_column('order', 'total_price')
    # op.add_column('emailsubscription', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'emailsubscription', type_='foreignkey')
    op.drop_index(op.f('ix_emailsubscription_verification_token'), table_name='emailsubscription')
    op.drop_index(op.f('ix_emailsubscription_user_id'), table_name='emailsubscription')
    op.drop_column('emailsubscription', 'verified')
    op.drop_column('emailsubscription', 'verification_token')
    op.drop_column('emailsubscription', 'unsubscribed_at')
    op.drop_column('emailsubscription', 'subscribed_at')
    op.drop_column('emailsubscription', 'user_id')
    op.drop_constraint(None, 'cartitem', type_='foreignkey')
    op.drop_index(op.f('ix_cartitem_variant_id'), table_name='cartitem')
    op.drop_column('cartitem', 'variant_id')
    op.create_table('paymentwebhookevent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_key', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('provider_event_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='paymentwebhookevent_pkey')
    )
    op.create_index('ix_paymentwebhookevent_reference', 'paymentwebhookevent', ['reference'], unique=False)
    # op.create_index('ix_paymentwebhookevent_event_key', 'paymentwebhookevent', ['event_key'], unique=True)
    op.create_table('paymentintent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='paymentintent_order_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='paymentintent_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='paymentintent_pkey')
    )
    op.create_index('ix_paymentintent_user_id', 'paymentintent', ['user_id'], unique=False)
    op.create_index('ix_paymentintent_reference', 'paymentintent', ['reference'], unique=True)
    op.create_index('ix_paymentintent_order_id', 'paymentintent', ['order_id'], unique=False)
    # ### end Alembic commands ###
